name: Scrape Exchange Rates

on:
  schedule:
    - cron: "33 3 * * 1-5"  # Run on weekdays at 333am UTC

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas html2image datetime

      - name: Run scraping script
        run: python scrape_exchange_rates.py # Assuming script name is scrape_exchange_rates.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update exchange rates data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # or your desired branch
